#!/usr/bin/env ruby

require 'pathname'

Pathname.glob('articles/**/*.md') do |pathname|
  content = pathname.read
  content.gsub!(/\n\n!\[(.*)\]\((.+)\)\n(.+)\n\n/) do
    alt = Regexp.last_match(1)
    url = Regexp.last_match(2)
    caption = Regexp.last_match(3)
    %<\n\n![#{alt}](#{url} "#{caption}")\n\n>
  end
  pathname.write(content)
end
