name: import

on:
  schedule:
    - cron: "0 19 * * *"
  workflow_dispatch:

jobs:
  import:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      id-token: write
    steps:
      - uses: google-github-actions/auth@v0
        with:
          service_account: ${{ secrets.GOOGLE_SERVICE_ACCOUNT }}
          workload_identity_provider: ${{ secrets.GOOGLE_WORKLOAD_IDENTITY_PROVIDER }}
      - uses: r7kamura/google-docs-to-github@v3
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          google_drive_folder_id: ${{ secrets.GOOGLE_DRIVE_FOLDER_ID }}
