name: test

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-ruby@v1
        with:
          ruby-version: '2.7.2'
      - run: bundle install --jobs=$(($(nproc) - 1)) --retry=1
      - run: bundle exec rake build
