name: test

on:
  pull_request:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v2
      - uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true
          ruby-version: '2.7.2'
      - run: echo "::add-matcher::.github/matchers/rubocop.json"
      - run: bundle install --jobs=$(($(nproc) - 1)) --retry=1
      - run: bundle exec rubocop --parallel
      - run: bundle exec rake build
